name: Security Scan

on:
  push:
    branches:
      - master
      - release/*
  schedule:
    - cron: "23 18 * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          DOCKER_BUILDKIT=1 docker build . \
            --build-arg RUNTIMES=all \
            -t $MLSERVER_IMAGE
        env:
          MLSERVER_IMAGE: seldonio/mlserver:${{ github.sha }}
      - uses: snyk/actions/setup@master
      - name: Scan Docker Image
        continue-on-error: true
        run: |
          snyk container test \
            seldonio/mlserver:${{ github.sha }} \
            --fail-on=upgradable \
            --app-vulns \
            --severity-threshold=high \
            --file=Dockerfile \
            --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
